name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  test:
    name: Test ruby version matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3', 'head', 'truffleruby-head'] # keep in sync with gemspec
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake test

  rubocop:
    name: Run rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # lowest supported version, keep in sync with .rubocop.yml
          bundler-cache: true
      - run: bundle exec rake rubocop
